version: '3'
services:
  app:
    build: .
    image: joaoseidel/message
    ports:
      - 8080:8080
    networks:
      - spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password123
      - TZ=GMT
    ports:
      - 5432:5432
    networks:
      - spring
networks:
  spring:
    driver: bridge